version: '3.8'

services:

  manager:
    container_name: manager
    hostname: manager
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - drones_net
    volumes:
      - ./app:/srv/app
      - ./main.py:/srv/main.py
    ports:
      - 8001:8000
    env_file:
      - .env.db
    depends_on:
      - manager_mongo

  manager_mongo:
    image: mongo:5.0
    restart: always
    hostname: manager_mongo
    env_file:
      - .env.mongo
    ports:
      - 27000:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - drones_net

networks:
  drones_net:
    driver: bridge

volumes:
  data: